### ISSUE TITLE
PasteScript is not installed

### ISSUE THREAD

**Issue by woutervh** [Pylons/pyramid_jqm#3]
PasteScript is not installed when installing pyramid_jqm in a fresh virtualenv.
A bug or a feature?

The docs refer to paster to generate the code from the scaffold:

> /path/to/paster create -t pyramid_jqm_starter MyApp

but PasteScript is not specified as a dependency in pyramid_jqm.
Is it intended that you to install it yourself, since PasteScript  itself is dropped as a dependency in pyramid1.3.

**Comment by mcdonc** [comment]
I've made a new release of pyramid_jqm to PyPI that should fix this.  Please read its instructions.
